# Generated by Django 4.2.27 on 2026-01-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_badge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgerequirements',
            old_name='description',
            new_name='requirement',
        ),
        migrations.AlterField(
            model_name='badgerequirements',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='add_badge.badge'),
        ),
    ]
