# Generated by Django 4.2.27 on 2026-01-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_badge', '0003_rename_requirement_badgerequirements_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgerequirements',
            old_name='description',
            new_name='requirement',
        ),
    ]
