# Generated by Django 4.2.27 on 2026-01-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_badge', '0004_rename_description_badgerequirements_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgerequirements',
            old_name='requirement',
            new_name='text',
        ),
    ]
