# Generated by Django 4.2.27 on 2026-01-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patrols'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patrols'),
        ),
    ]
