# Generated by Django 4.2.27 on 2026-01-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_updated_on_post_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posst',
            new_name='post',
        ),
    ]
